version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=1234
      - DB_NAME=LMS
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: LMS
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge